### ISSUE TITLE
What is the motivation?

### ISSUE THREAD

**Issue by tyt2y3** [ClementTsang/polify#1]
Hello I found your work via the bottom utility. Well that was a nice app.
What is the motivation behind this project?
Can you also outline a bit of your implementation strategy?
I ask these questions purely out of academic curiosity.
I have done something similar in spirit with this project, that might also interest you!
Please checkout https://github.com/visioncortex/visionmagic

**Comment by ClementTsang** [comment]
> Motivation

The answer is kinda simple tbh - just for fun.  I had looked into the idea of creating a tool for "polifying" images for a while now (probably over a year ago), and it seemed like a fun little project.  I only recently (relatively speaking) had time to give it a shot.

It isn't really a project I intended for "serious" use, I guess (at least in its current form).  It's mostly one done for fun.

As for why I did it in the way I did (WASM support, written in Rust), it was again mostly for fun, as well as just as a good "reason" to dip my toes into the WASM space, and seeing how integrating a WASM library into a web application/page would go.  And it was pretty fun!

> Implementation strategy

I heavily based most of the algorithm on [this paper](https://cjqian.github.io/docs/tri_iw_paper.pdf) by Crystal J. Qian, modified to work with image-rs and imageproc as required.  There are certainly improvements to make to both the library and the WASM implementation.

---

I'll definitely also check out your project!
